;;; nibelung-theme-base.el --- Base theme generator -*- lexical-binding: t; -*-

(defun nibelung-theme-create (theme-name palette)
  "Create a theme with THEME-NAME using colors from PALETTE."
  (let* ((bg            (plist-get palette :bg))
         (fg            (plist-get palette :fg))
         (level0        (plist-get palette :level0))
         (level1        (plist-get palette :level1))
         (level2        (plist-get palette :level2))
         (level3        (plist-get palette :level3))
         (level4        (plist-get palette :level4))
         (level5        (plist-get palette :level5))
         (level6        (plist-get palette :level6))
         (accent-subtle       (plist-get palette :accent-subtle))
         (accent-light        (plist-get palette :accent-light))
         (accent-bright       (plist-get palette :accent-bright))
         (accent-match        (plist-get palette :accent-match))
         (emphasis            (plist-get palette :emphasis))
         (link-color          (plist-get palette :link))
         (string-bg           (plist-get palette :string-bg))
         (comment-bg          (plist-get palette :comment-bg))
         (rainbow-blue       (plist-get palette :rainbow-blue))
         (rainbow-red        (plist-get palette :rainbow-red))
         (rainbow-orange     (plist-get palette :rainbow-orange))
         (rainbow-yellow     (plist-get palette :rainbow-yellow))
         (rainbow-green      (plist-get palette :rainbow-green))
         (rainbow-cyan       (plist-get palette :rainbow-cyan))
         (rainbow-bluelight  (plist-get palette :rainbow-bluelight))
         (rainbow-magenta    (plist-get palette :rainbow-magenta))

         ;; FACES definitions
         (bold `((t (:foreground ,emphasis))))
         (builtin `((t (:foreground ,level3))))
         (code-block `((t (:extend t :background ,level0))))
         (code-block-header `((t (:extend t :background ,level1 :foreground ,fg))))
         (comment `((t (:extend t :background ,comment-bg :foreground ,level3))))
         (constant `((t (:foreground ,level4))))
         (cursor `((t (:inverse-video t :background ,fg :foreground ,bg))))
         (default `((t (:foreground ,fg :background ,bg))))
         (function `((t (:foreground ,level5))))
         (header `((t (:background ,level4 :foreground ,level0))))
         (header-not-extended `((t (:extend nil :background ,level4 :foreground ,level0))))
         (highlight `((t (:override t :background ,level4 :foreground ,level0 :distant-foreground ,level0))))
         (link `((t (:foreground ,link-color :underline t))))
         (lpadding '(:box (:line-width (10 . 1) :style flat-button)))
         (match `((t (:background ,emphasis :foreground ,level1))))
         (modeline `((t (:background ,fg :foreground ,level0))))
         (modeline-indicator header)
         (modeline-white `((t (:foreground ,level5 :background ,level0))))
         (optional `((t (:foreground ,level2))))
         (org-done `((t (:background ,bg :foreground ,fg :height 0.95 ,@lpadding))))
         (org-todo* `((t (:background ,fg :foreground ,bg :height 0.95 ,@lpadding))))
         (replace-confirm `((t (:background ,level4 :foreground ,level0))))
         (replace-match* `((t (:background ,level5 :foreground ,level0))))
         (string* `((t (:background ,string-bg :foreground ,level6))))
         (symbol `((t (:foreground ,level5))))
         (text `((t (:foreground ,fg :weight normal :normal t))))
         (type builtin)
         (variable constant))

    (custom-theme-set-faces
     theme-name
     `(default ,default)
     `(cursor ,cursor)
     `(highlight ,highlight)
     `(hl-line ,highlight)
     ;; Constant
     `(font-lock-builtin-face ,builtin)
     `(font-lock-preprocessor-face ,type)
     `(font-lock-constant-face ,constant)
     `(font-lock-function-call-face ,link)
     `(highlight-quoted-symbol ,symbol)
     `(font-lock-keyword-face ,optional)
     `(clojure-keyword-face ,builtin)
     `(font-lock-string-face ,string*)
     `(font-lock-type-face ,type)
     `(font-lock-function-name-face ,function)
     `(font-lock-variable-name-face ,variable)
     `(font-lock-bracket-face ,optional)
     `(tree-sitter-hl-face:punctuation ,optional)
     `(tree-sitter-hl-face:punctuation.delimiter ,optional)
     `(font-lock-escape-face ,optional)
     `(font-lock-operator-face ,optional)
     ;; Comment
     `(font-lock-comment-delimiter-face ,comment)
     `(font-lock-comment-face ,comment)
     `(font-lock-doc-face ,optional)
     `(font-lock-warning-face ((t (:foreground ,fg))))
     ;; Misc
     `(shadow ,optional)
     `(whitespace-tab ,optional)
     `(sh-quoted-exec ,optional)
     `(line-number ((t (:background ,bg :foreground ,fg))))
     `(message-header-newsgroups ,text)
     `(message-header-xheader ,text)
     `(message-header-cc ,text)
     `(message-header-to ,text)
     `(minibuffer-prompt ,code-block-header)
     `(marginalia-documentation ,optional)
     `(custom-set ,text)
     `(icon ,optional)
     `(+fold-hideshow-folded-face ,optional)
     `(read-multiple-choice-face ,text)
     `(helpful-heading ,comment)
     ;; Custom Menu
     `(custom-variable-tag ,variable)
     `(custom-variable-documentation ,optional)
     `(custom-documentation ,optional)
     `(custom-state ,bold)
     `(custom-visibility ,bold)
     `(custom-group-tag ,header)
     `(custom-button-unraised ,constant)
     `(custom-button ,function)
     `(custom-button-mouse ,header)
     `(widget-field ,symbol)
     `(widget-unselected ,optional)
     ;; Company
     (setq company-format-margin-function nil)
     `(company-tooltip ,function)
     `(company-tooltip-common ,match)
     `(company-tooltip-selection ,header)
     `(company-tooltip-scrollbar-thumb ,header)
     `(company-tooltip-scrollbar-track ,variable)
     `(company-echo-common ,variable)
     `(company-tooltip-annotation ,variable)
     ;; Match
     `(evil-ex-lazy-highlight ,match)
     `(match ,match)
     `(region ,match)
     `(bold ,bold)
     `(orderless-match-face-0 ,match)
     `(orderless-match-face-1 ,match)
     `(show-paren-match ,match)
     `(isearch ,replace-match*)
     `(lazy-highlight ,replace-match*)
     `(evil-ex-substitute-replacement ,replace-confirm)
     `(orderless-match-face-2 ,bold)
     `(orderless-match-face-3 ,bold)
     ;; Warnings
     `(success ,optional)
     `(warning ,header)
     `(error ,header)
     `(flymake-error ((t (:extend t :background ,emphasis :foreground ,fg))))
     `(flymake-warning ((t (:underline (:color ,emphasis :style line :position t)))))
     ;; Modeline
     `(doom-nano-modeline-evil-insert-state-face ,modeline-indicator)
     `(doom-nano-modeline-evil-motion-state-face ,modeline-indicator)
     `(doom-nano-modeline-evil-visual-state-face ,modeline-indicator)
     `(doom-nano-modeline-evil-emacs-state-face ,modeline-indicator)
     `(doom-nano-modeline-evil-operator-state-face ,modeline-indicator)
     `(doom-nano-modeline-evil-normal-state-face ,modeline-indicator)
     `(doom-nano-modeline-inactive ,modeline-white)
     `(doom-nano-modeline-cursor-position-face ,modeline)
     `(doom-nano-modeline-vc-branch-name-face ,modeline-indicator)
     `(mode-line ,modeline)
     `(mode-line-buffer-id ,modeline)
     `(mode-line-emphasis ,modeline)
     `(mode-line-highlight ,modeline)
     `(mode-line-faces ,modeline)
     `(mode-line-inactive ,modeline-white)
     `(doom-dashboard-loaded ,builtin)
     ;; Links
     `(diary ,link)
     `(link ,link)
     ;; Org Mode
     `(+org-todo-cancel ,code-block-header)
     `(org-hide ((t (:foreground ,bg))))
     `(org-agenda-date ,text)
     `(org-agenda-date-today ,code-block-header)
     `(org-agenda-date-weekend ,text)
     `(org-agenda-done ,optional)
     `(org-agenda-structure ,text)
     `(org-block ,code-block)
     `(org-quote ,code-block)
     `(org-block-begin-line ,code-block-header)
     `(org-block-end-line ,code-block-header)
     `(org-done ,optional)
     `(org-document-title ,constant)
     `(org-ellipsis ,optional)
     `(org-headline-done ,optional)
     `(org-list-dt ,constant)
     `(org-meta-line ,constant)
     `(org-modern-done ,org-done)
     `(org-modern-block-name ,constant)
     `(org-modern-label ,org-todo*)
     `(org-modern-todo ,org-todo*)
     `(org-modern-tag ,org-done)
     `(org-modern-date-active ,org-todo*)
     `(org-modern-date-inactive ,org-done)
     `(org-modern-time-active ,org-todo*)
     `(org-modern-time-inactive ,org-done)
     `(org-modern-progress-complete ,org-done)
     `(org-modern-progress-incomplete ,org-todo*)
     `(org-modern-priority ((t (:background ,level3
                                :foreground ,fg
                                :box (:line-width (2 . 1)
                                      :color ,bg
                                      :style flat-button)))))
     `(org-formula ,match)
     `(org-document-info ,symbol)
     `(org-todo ,org-todo*)
     `(org-tag ,function)
     `(org-date ,link)
     `(org-drawer ,optional)
     `(org-checkbox ,optional)
     `(org-list-dt ,optional)
     `(outline-3 ,constant)
     `(outline-2 ,symbol)
     `(outline-1 ,function)
     `(outline-4 ,bold)
     `(markdown-header-face-3 ((t (:foreground ,level4))))
     `(markdown-header-face-2 ((t (:foreground ,level5))))
     `(markdown-header-face-1 ((t (:foreground ,level6))))
     `(markdown-header-face-4 ((t (:foreground ,rainbow-blue))))
     `(org-table ,constant)
     ;; Dired
     `(diredfl-file-suffix ,constant)
     `(diredfl-compressed-file-suffix ,constant)
     `(diredfl-file-name ,text)
     `(diredfl-dir-name ,code-block-header)
     `(diredfl-dir-heading ,code-block-header)
     `(diredfl-ignored-file-name ,optional)
     `(diredfl-ignored ,optional)
     `(diredfl-symlink ,link)
     `(dgi-commit-message-face ,optional)
     `(diredfl-dir-priv ,text)
     `(diredfl-exec-priv ,text)
     `(diredfl-no-priv ,optional)
     `(diredfl-link-priv ,text)
     `(diredfl-read-priv ,optional)
     `(diredfl-write-priv ,optional)
     `(diredfl-rare-priv ,text)
     `(diredfl-date-time ,optional)
     `(diredfl-number ,constant)
     `(diredfl-deletion ,replace-confirm)
     `(diredfl-deletion-file-name ,replace-confirm)
     `(help-key-binding ,text)
     ;; Rainbow delimiters
     `(rainbow-delimiters-depth-4-face ((t (:foreground ,level4))))
     `(rainbow-delimiters-depth-3-face ((t (:foreground ,rainbow-blue))))
     `(rainbow-delimiters-depth-2-face ((t (:foreground ,level3))))
     `(rainbow-delimiters-depth-1-face ((t (:foreground ,accent-light))))
     `(rainbow-delimiters-unmatched-face ,header)
     `(rainbow-delimiters-base-error-face ,header)
     `(rainbow-delimiters-mismatched-face ,header)
     ;; Magit
     `(magit-tag ,header)
     `(magit-section-highlight ((t (:background ,bg :foreground ,fg))))
     `(magit-diff-context-highlight ((t (:foreground ,fg))))
     `(magit-branch-local ,match)
     `(magit-branch-remote ,header)
     `(magit-section-heading ,code-block-header)
     `(magit-branch-current ,match)
     `(magit-hash ,optional)
     `(magit-reflog-commit ,comment)
     `(magit-diff-added ,replace-match*)
     `(magit-diff-added-highlight ,replace-match*)
     `(magit-diff-removed ,replace-confirm)
     `(magit-diff-removed-highlight ,replace-confirm)
     `(diff-refine-added ,match)
     `(diff-refine-removed ,variable)
     `(magit-diff-removed-highlight ,variable)
     `(magit-diff-lines-heading ,match)
     `(magit-section-heading ,variable)
     `(magit-diff-hunk-heading ,constant)
     `(magit-diff-hunk-heading-highlight ,constant)
     `(magit-diff-file-heading ,symbol)
     `(magit-diffstat-added ,match)
     `(magit-diffstat-removed ,variable)
     `(magit-log-author ,optional)
     ;; Transient
     `(transient-key-stay ,text)
     `(transient-key-exit ,constant)
     `(transient-heading ,code-block-header)
     `(transient-value ,match)
     `(transient-argument ,match)
     ;; Treesitter
     `(ts-fold-replacement-face ,optional)
     ;; Cider
     `(cider-result-overlay-face ,modeline-indicator)
     `(cider-test-success-face ,match)
     `(cider-error-overlay-face ,replace-confirm)
     `(cider-test-failure-face ,replace-confirm)
     `(cider-instrumented-face ,link)
     ;; Eshell
     `(eshell-syntax-highlighting-shell-command-face ,bold)
     `(eshell-prompt ,optional)
     `(eshell-syntax-highlighting-invalid-face ,match)
     ;; Colors
     `(ansi-color-black          ((t (:foreground ,level6))))
     `(ansi-color-blue           ((t (:foreground ,rainbow-blue))))
     `(ansi-color-bright-black   ((t (:foreground ,level5))))
     `(ansi-color-bright-blue    ((t (:foreground ,rainbow-cyan))))
     `(ansi-color-bright-cyan    ((t (:foreground ,rainbow-green))))
     `(ansi-color-bright-green   ((t (:foreground ,rainbow-green))))
     `(ansi-color-bright-magenta ((t (:foreground ,rainbow-yellow))))
     `(ansi-color-bright-red     ((t (:foreground ,rainbow-red))))
     `(ansi-color-bright-white   ((t (:foreground ,rainbow-bluelight))))
     `(ansi-color-bright-yellow  ((t (:foreground ,rainbow-yellow))))
     `(ansi-color-cyan           ((t (:foreground ,rainbow-cyan))))
     `(ansi-color-faint          ((t (:foreground ,rainbow-orange))))
     `(ansi-color-fast-blink     ((t (:foreground ,rainbow-blue))))
     `(ansi-color-green          ((t (:foreground ,rainbow-green))))
     `(ansi-color-inverse        ((t (:foreground ,rainbow-orange))))
     `(ansi-color-italic         ((t (:foreground ,rainbow-bluelight))))
     `(ansi-color-magenta        ((t (:foreground ,rainbow-magenta))))
     `(ansi-color-red            ((t (:foreground ,rainbow-red))))
     `(ansi-color-slow-blink     ((t (:foreground ,rainbow-magenta))))
     `(ansi-color-underline      ,link)
     `(ansi-color-white          ((t (:foreground ,rainbow-orange))))
     `(ansi-color-yellow         ((t (:foreground ,rainbow-yellow))))
     `(ansi-color-bold ,bold))))

(provide 'nibelung-theme-base)
;;; nibelung-theme-base.el ends here